In [70]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,OrdinalEncoder

In [71]:
df=pd.read_csv("C:/Users/LENOVO/Desktop/MCA/data science/Shopping_Customer_Dataset")

In [72]:
df

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10
...,...,...,...,...,...,...,...
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [73]:
df.head()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5
4,Male,Sports,PayPal,Silver,Los Angeles,4.8,10

In [74]:
df.tail()

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
995,Male,Clothing,Credit Card,Bronze,Houston,4.0,7
996,Female,Beauty,Credit Card,Silver,Houston,2.1,7
997,Male,Sports,Debit Card,Silver,Miami,2.3,8
998,Female,Beauty,PayPal,Gold,Houston,4.7,2
999,Male,Home & Kitchen,PayPal,Silver,Miami,1.2,9

In [75]:
df.size

7000

In [76]:
df.shape

(1000, 7)

In [77]:
df.columns.tolist()

['Gender',
 'Product_Category',
 'Payment_Method',
 'Membership_Level',
 'City',
 'Customer_Rating',
 'Total_Items']

In [78]:
df.isnull().sum()

Gender              27
Product_Category     0
Payment_Method       0
Membership_Level     0
City                 0
Customer_Rating     28
Total_Items          0
dtype: int64

In [79]:
num_col=df.select_dtypes(include="number").columns

In [80]:
df[num_col]=df[num_col].fillna(df[num_col].median())

In [81]:
df.isnull().sum()

Gender              27
Product_Category     0
Payment_Method       0
Membership_Level     0
City                 0
Customer_Rating      0
Total_Items          0
dtype: int64

In [82]:
cat_col=df.select_dtypes(include=["object","category"]).columns

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_10352\3948372773.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_col=df.select_dtypes(include=["object","category"]).columns

In [83]:
for col in cat_col:
    if df[col].isnull().any() and not df[col].mode().empty:
        df[col]=df[col].fillna(df[col].mode()[0])

In [84]:
df.isnull().sum()

Gender              0
Product_Category    0
Payment_Method      0
Membership_Level    0
City                0
Customer_Rating     0
Total_Items         0
dtype: int64

In [85]:
df.drop_duplicates(inplace=True)

In [86]:
if "Date" in df.columns:
    df["date"]=pd.to_datetime(df["Date"],errors="coerce")

In [87]:
df.dtypes

Gender                  str
Product_Category        str
Payment_Method          str
Membership_Level        str
City                    str
Customer_Rating     float64
Total_Items           int64
dtype: object

In [88]:
df.loc[0:3, :]

,Gender,Product_Category,Payment_Method,Membership_Level,City,Customer_Rating,Total_Items
0,Male,Beauty,Cash,Premium,Chicago,4.6,8
1,Female,Home & Kitchen,PayPal,Bronze,Chicago,4.2,2
2,Female,Sports,Debit Card,Silver,Miami,3.7,9
3,Female,Electronics,Cash,Silver,New York,3.7,5

In [89]:
df.iloc[0:5,0:2]

   Gender Product_Category
0    Male           Beauty
1  Female   Home & Kitchen
2  Female           Sports
3  Female      Electronics
4    Male           Sports

In [90]:
if "Gender" in df.columns:
    print(df[df["Gender"]=="Female"])

     Gender Product_Category Payment_Method Membership_Level         City  \
1    Female   Home & Kitchen         PayPal           Bronze      Chicago
2    Female           Sports     Debit Card           Silver        Miami
3    Female      Electronics           Cash           Silver     New York
7    Female      Electronics           Cash           Silver      Houston
8    Female           Beauty    Credit Card           Silver     New York
..      ...              ...            ...              ...          ...
991  Female           Sports         PayPal           Silver        Miami
992  Female      Electronics         PayPal             Gold  Los Angeles
993  Female         Clothing    Credit Card           Bronze  Los Angeles
996  Female           Beauty    Credit Card           Silver      Houston
998  Female           Beauty         PayPal             Gold      Houston

     Customer_Rating  Total_Items
1                4.2            2
2                3.7            9
3                3.7            5
7                2.1            3
8                1.9           10
..               ...          ...
991              2.1            7
992              3.5            3
993              2.8            6
996              2.1            7
998              4.7            2

[526 rows x 7 columns]

In [91]:
if "Total_Items" in df.columns:
    df["t*2"]=df["Total_Items"]*2
    print(df["t*2"])
    df[["t*2","Total_Items"]].head()

0      16
1       4
2      18
3      10
4      20
       ..
995    14
996    14
997    16
998     4
999    18
Name: t*2, Length: 999, dtype: int64

In [92]:
if "Gender" in df.columns:
   print(df.groupby("Gender").size())

Gender
Female    526
Male      473
dtype: int64

In [93]:
if "Gender" in df.columns:
    le=LabelEncoder()
    df["G_encoder"]=le.fit_transform(df["Gender"].astype(str))

In [94]:
print(df[["Gender", "G_encoder"]].head())

   Gender  G_encoder
0    Male          1
1  Female          0
2  Female          0
3  Female          0
4    Male          1

In [95]:
if "Payment_Method" in df.columns:
    df=pd.get_dummies(df,columns=["Payment_Method"],dtype=int)
    print(df.head())

   Gender Product_Category Membership_Level         City  Customer_Rating  \
0    Male           Beauty          Premium      Chicago              4.6
1  Female   Home & Kitchen           Bronze      Chicago              4.2
2  Female           Sports           Silver        Miami              3.7
3  Female      Electronics           Silver     New York              3.7
4    Male           Sports           Silver  Los Angeles              4.8

   Total_Items  t*2  G_encoder  Payment_Method_Cash  \
0            8   16          1                    1
1            2    4          0                    0
2            9   18          0                    0
3            5   10          0                    1
4           10   20          1                    0

   Payment_Method_Credit Card  Payment_Method_Debit Card  \
0                           0                          0
1                           0                          0
2                           0                          1
3                           0                          0
4                           0                          0

   Payment_Method_PayPal
0                      0
1                      1
2                      0
3                      0
4                      1

In [98]:
if "Membership_Level" in df.columns:
    oe=OrdinalEncoder(
        categories=[["Bronze", "Silver", "Gold", "Premium"]])

In [99]:
df["Membership_Level_encoded"]=oe.fit_transform(
    df[["Membership_Level"]])

In [100]:
 print(df[["Membership_Level", "Membership_Level_encoded"]].head())

  Membership_Level  Membership_Level_encoded
0          Premium                       3.0
1           Bronze                       0.0
2           Silver                       1.0
3           Silver                       1.0
4           Silver                       1.0

In [101]:
df.head()

,Gender,Product_Category,Membership_Level,City,Customer_Rating,Total_Items,t*2,G_encoder,Payment_Method_Cash,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_PayPal,Membership_Level_encoded
0,Male,Beauty,Premium,Chicago,4.6,8,16,1,1,0,0,0,3.0
1,Female,Home & Kitchen,Bronze,Chicago,4.2,2,4,0,0,0,0,1,0.0
2,Female,Sports,Silver,Miami,3.7,9,18,0,0,0,1,0,1.0
3,Female,Electronics,Silver,New York,3.7,5,10,0,1,0,0,0,1.0
4,Male,Sports,Silver,Los Angeles,4.8,10,20,1,0,0,0,1,1.0

In [102]:
df.shape

(999, 13)